version: '3'

services:
  eslint_container:
    build:
      context: ../
      dockerfile: ./docker/eslintContainer/Dockerfile
    tty: true
    volumes:
      # for test
      #      - ../service:/app/service
      # for xdevkit
      #      - ../../../../service:/app/service
      - ${SERVICE_PATH}:/app/service
      - ../src/setting:/app/setting:ro
 
    command: sh -c "yarn eslint ${FIX_OPTION} --config ./setting/.eslintrc.json 'service/**/*.js'"


